### PR TITLE
Add opencadd.databases.klifs module

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description
Integrate [`klifs_utils` package](https://github.com/volkamerlab/klifs_utils) into `opencadd` in the form of the `opencadd.databases.klifs` module.

## Todos
  - [x] Move `klifs_utils` code to `opencadd.databases.klifs`
    - Code from https://github.com/volkamerlab/klifs_utils/tree/extend_coordinates, i.e. the `extend_coordinates` branch with simplifications of the `coordinates` module as described in PR https://github.com/volkamerlab/klifs_utils/pull/10
  - [x] Update imports and `__init__.py` files.
  - [x] Update and run tutorial (instead of running unit test, which do not exist yet): `docs/tutorials/klifs.ipydb`
  - [x] Update `devtools/conda-envs/test_env.yml`
  - [x] Add `klifs` tests (skeleton) to `opencadd.tests.databases.test_databases_klifs.py` and test data to `opencadd/tests/databases/data/`
  - [x] Run `black` reformatter
  - [x] Add `sphinx` documentation to `docs/index.rst`
    - Description: `docs/databases_klifs.rst`
    - Tutorial: `docs/tutorials/databases_klifs.rst`

## Questions
  - [x] Where to add module dependencies? Currently `devtools/conda-envs/test_env.yml`.
  - [x] Where to add unit tests and data for `klifs` module? Currently `opencadd.tests.databases`.
  - [x] Where to add a README for the `opencadd.databases.klifs` module? `opencadd/databases/klifs/README.md`? > Added in the form of a sphinx documentation in `docs/databases_klifs.rst`.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by dominiquesydow** [comment]
@jaimergp, whenever the test checks are done (they are in waiting mode for quite a while already), could you review this PR, please? 
The main aim here is to integrate the existing `klifs_utils` code into the `opencadd` package.

In the next PR, I plan to simplify the API a bit and add unit testing, thus I suggest reviewing here only the package-level part - and the API next time.

**Comment by dominiquesydow** [comment]
My main question is if I put the testing and environment bits at the right position within the package (see PR Questions).

**Comment by dominiquesydow** [comment]
@jaimergp, coming back to the still pending checks. Is it possible that the checks "test (xxx)" are outdated? 
https://github.community/t/expected-waiting-for-status-to-be-reported/16727

When I look into the protected branch settings, I see (only part of it shown):
image

The "Test on xxx" checks match with the `ci.yaml` configs:
https://github.com/volkamerlab/opencadd/blob/master/.github/workflows/ci.yaml

Maybe we need to check those instead?

**Comment by jaimergp** [comment]
Yep, good catch, this was inherited from the previous `superposer` configs. Reviewing now.

**Comment by jaimergp** [comment]
All good! This was an excellent PR. Thanks for your contribution!

**Pull request merged**
