### PR TITLE
Install package in docs CI too

### PR DESCRIPTION
**Pull request by jaimergp**
Make sure CI docs pass and can be deployed to RTD

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by jaimergp** [comment]
@dominiquesydow -- there's two warnings that I think concern your newly added notebooks:

```
/home/runner/work/opencadd/opencadd/docs/20201013_opencadd_new_features_slides.ipynb: WARNING: document isn't included in any toctree
checking consistency... done
/home/runner/work/opencadd/opencadd/docs/notebooks/klifs_kinase_names.ipynb: WARNING: document isn't included in any toctree
preparing documents... done
```

**Comment by dominiquesydow** [comment]
Oh, sorry! I was not aware that any notebooks in docs/ will be monitored.

Maybe they live in the wrong place.

There first is my group seminar notebook (slides) - I added it next to the superposition slides

The second is more an exploratory notebook that I used to make some decisions on the kinase names provided in KLIFS. 

What do you suggest?

**Comment by jaimergp** [comment]
Do you think they add some value to the docs? If that's the case, we can put them in an "unsorted category" with "more resources" for the "curious minds" (I can't seem to stop "quoting" "something" every three words 😄)

If you don't want them rendered in the docs, we can put them in other directory (even within docs/, but change the configuration so it ignores that directory -- assuming there's such a way).

**Comment by jaimergp** [comment]
I moved them to `docs/other` along with other files, and set that directory as `excluded`. Do you agree @dominiquesydow ?

**Comment by dominiquesydow** [comment]
That sounds very good to me. Ready to be merged.

**Pull request merged**
