### PR TITLE
Base branch for `superposer` updates

### PR DESCRIPTION
**Pull request by dominiquesydow**
## Description
This is the base branch for @pipaj97 changes to `superposer` that were needed in context of his benchmarking.
The benchmark (topic of the bachelor thesis) used this branch for the alignments.
Commits until PR #114 are preparatory steps. 
So the commits of PR #114 and later are the changes made to improve the results of the benchmark (part of the bachelor thesis).

## Todos
PR #90 
  - [x] Fix parsing of method options for superposer.
 ______
PR #94 
  - [x] Output structure lengths in CLI
  - [x] Get coverage for each method
  - [x] Output coverage of alignment in CLI
  - [x] Output coverage of alignment in CLI
  ______
PR #114 
  - [x] Add Clustal Omega as optional sequence alignment tool for TheseusAligner
  ______
PR #115 
  - [x] Add selection command to CLI
  - [x] Add selection  functionality to API
  - [x] Add selection  functionality to Aligners
  - [x] Update tests

______
NEW
 - [x] Add Clustal Omega as optional sequence alignment tool for MDAnalysisAligner

## Status
- [x] Ready to go (merge after thesis to ensure reproducibility, since the thesis used this branch - for that the current master should first be merged into this branch. That should also fix the open merge conflict in the test_env.yaml)

### CODE REVIEW

**Comment by pipaj97** [comment]
Hi @dominiquesydow,

the PR #115 contains my previous PRs. So it contains the other mentioned too.

PR #94 contains PR #90, PR #114 contains PR #94 and PR #115 contains PR #114.

**Comment by dominiquesydow** [comment]
Ok, thanks! Sorry I started with https://github.com/volkamerlab/opencadd/pull/114. 

Let's first finish the review on https://github.com/volkamerlab/opencadd/pull/114 and merge it - and then continue in this order 
- https://github.com/volkamerlab/opencadd/pull/90
- https://github.com/volkamerlab/opencadd/pull/94
- https://github.com/volkamerlab/opencadd/pull/115

**Comment by dominiquesydow** [comment]
CI is failing probably due to connection timeouts for this method (reported as 404 errors): 

https://github.com/volkamerlab/opencadd/blob/d46ca3eb0cc90a47a55f21fa9675f53112b8b801/opencadd/structure/core.py#L17-L20

Possible solution:
- Add `redo` decorator to this method (see an example [here](https://projects.volkamerlab.org/teachopencadd/talktorials/T008_query_pdb.html?highlight=redo#Select-PDB-entries-with-the-hightest-resolution))
- Add a test for the `opencadd.structure.core` module, especially for the `Structure.from_pdbid` method
- Hope this is enough to make the CI pass (also for the `superposer` tests that are failing at the moment)

**Comment by pipaj97** [comment]
> CI is failing probably due to connection timeouts for this method (reported as 404 errors):
> 
> https://github.com/volkamerlab/opencadd/blob/d46ca3eb0cc90a47a55f21fa9675f53112b8b801/opencadd/structure/core.py#L17-L20
> 
> Possible solution:
> 
> * Add `redo` decorator to this method (see an example [here](https://projects.volkamerlab.org/teachopencadd/talktorials/T008_query_pdb.html?highlight=redo#Select-PDB-entries-with-the-hightest-resolution))
> * Add a test for the `opencadd.structure.core` module, especially for the `Structure.from_pdbid` method
> * Hope this is enough to make the CI pass (also for the `superposer` tests that are failing at the moment)


CI failing is fixed implementing the redo decorator.

**Comment by dominiquesydow** [comment]
Hi @corey-taylor and @pipaj97, quickly checking in with you - what is the status of this PR?

**Comment by pipaj97** [comment]
> Hi @corey-taylor and @pipaj97, quickly checking in with you - what is the status of this PR?

Hi @dominiquesydow, I will finish this PR after the grading of the thesis is finished.
When the PR can be merged, I will ping you here again.

TODOs are: Merge the current master branch into this branch and resolve merge conflicts (should only be the env.yaml).

**Review by corey-taylor — APPROVED** [review]
All tests passed, good to go from my perspective.

**Pull request merged**
